### ISSUE TITLE
error lein uberjar  with AWT tool

### ISSUE THREAD

**Issue by PlumpMath** [cljfx/cljfx#119]
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Toolkit not initialized
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:410)
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:405)
	at javafx.application.Platform.runLater(Platform.java:152)
	at cljfx.renderer$request_render.invokeStatic(renderer.clj:44)
	at cljfx.renderer$create$render__12865.invoke(renderer.clj:78)
	at cljfx.renderer$mount.invokeStatic(renderer.clj:88)
	at cljfx.api$mount_renderer.invokeStatic(api.clj:325)
	at cljfx.api$create_app.invokeStatic(api.clj:498)
	at tray.pnix.tray$START$fn__22877.invoke(tray.clj:74)
	at clj_systemtray.core$add_listener_BANG_$fn__18042.invoke(core.clj:100)
	at clj_systemtray.core.proxy$java.lang.Object$ActionListener$c1f703.actionPerformed(Unknown Source)
	at java.desktop/java.awt.MenuItem.processActionEvent(MenuItem.java:690)
	at java.desktop/java.awt.MenuItem.processEvent(MenuItem.java:649)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	
	---------------------------------- 
	lein uberjar (and execute tray and exit popup(cljfx) below popup-QUIT window error 
	---------------------------------- code 
	
	(defn popup-QUIT []
  (fx/on-fx-thread
   (fx/create-component
    {:fx/type :stage
     :showing true
     :title "exit"
     :width 250
     :height 130
     :always-on-top true
     :resizable false
     :style :utility 
     :scene {:fx/type :scene
	     :root {:fx/type :v-box
		    :alignment :top-center
		    :children [
                               {:fx/type :label :text "\n"}
                               {:fx/type :label :text "exit?"}
                               {:fx/type :label :text "\n"}
                               {:fx/type :button :text "YES" :on-action (fn [_] (java.lang.System/exit 0))}
			       ]
                    }}}
    )))

;; ----------------------------------------

https://github.com/mbsmith/clj-systemtray

	        (TRAY/menu "system menu" (TRAY/menu-item "exit"
      (fn [x] (when (= "off" @FX/p-popup)  ;; <--- I want use context atom :showing flag
                        (FX/popup-QUIT) )))
     )

**Comment by frenchy64** [comment]
Could you post a complete example with cljfx?

**Comment by PlumpMath** [comment]
@frenchy64 Thanks.
.
Besides this problem, there was a problem that all the rendered letters and buttons disappeared later, so I removed all the cljfx and lowered it to the web.
.
(The cljfx experience was good.)
Like the story of the above question. 
I often use atom addwatch without re-frame experience. so That's the part of the data control flow is...
I didn't know how to automatically react to the cljfx subscription part and change it, so I just gave up. (the reason is I don't know concept lifetime & context & lifetime & no experience javafx)
.
After learning the re-frame properly, 
If I have a chance later, I'm thinking about trying cljfx again, 
And yet cljfx was very helpful and good. 
The neat design was really good. 
However, too difficult because I am no brain & experience :d.;;)
.
Currently, I'm thinking of looking at the vlaaad reveal code.
Thank you for your interest. and thanks vlaaad.
.

**Comment by frenchy64** [comment]
I found my experience with cljfx made learning re-frame much faster, learning one of them deeply should help with using both.

**Comment by PlumpMath** [comment]
I agree. nowday.. I want to go to the re-frame. then day I didn't understand the concept of subscribe and I couldn't implement the add-watch function in cljfx. so Even the re-frame does not understand. i'd like read tutorials with Re-frame and cljfx comparisons. Or I want both to need short implementations. yet i'm not thinking about cljfx because my work(web frontend). but I was first time fascinated with data orientated programming from cljfx. someday i hope re-try cljfx.
.
Oh, and let's talk about something else. I wish I could use it with cljfx and monkey game engine.
https://github.com/ertugrulcetin/jme-clj
 It would be even better if it could be developed for mobile use with.
