### ISSUE TITLE
Lein support?

### ISSUE THREAD

**Issue by ahungry** [cljfx/cljfx#14]
I can get this to work with openjdk 11 + deps.edn, however openjdk 11 + lein seems to run into a dead-end (cljfx.api init not being found on classpath etc.).

In talking in the clojurians clojure channel, some seem to be able to use this just fine with lein under an Oracle Java setup.

I added the dependency to project.clj and after `lein deps` could never get it to launch correctly.

Has anyone had any luck with lein + openjdk 11? (or lein + openjdk 8 with openjfx via package manager on a GNU/Linux box?)

**Comment by vlaaad** [comment]
Here is a minimal lein example I tried:
`project.clj`:
```edn
(defproject lein-cljfx-test "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [cljfx "1.2.9"]]
  :main lein-cljfx-test.core)
```
`src/lein_cljfx_test/core.clj`:
```clj
(ns lein-cljfx-test.core
  (:require [cljfx.api :as fx])
  (:gen-class)
  (:import [javafx.application Platform]))

(defn -main [& args]
  (Platform/setImplicitExit true)
  (fx/on-fx-thread
    (fx/create-component
      {:fx/type :stage
       :showing true
       :scene {:fx/type :scene
               :root {:fx/type :v-box
                      :children [{:fx/type :label
                                  :text "Hello from lein!"}]}}})))
```
Run from command line:
```sh
lein run
```
After running this command a window appeared with "Hello from lein!" text, can you try it and check if it works?

**Comment by ahungry** [comment]
Caused by: java.io.FileNotFoundException: Could not locate cljfx/api__init.class, cljfx/api.clj or cljfx/api.cljc on classpath.

Same error.

java -version                                                                                                                                                                                                 
openjdk version "11.0.3" 2019-04-16 

This is consistent on both Ubuntu 18.04 and Arch Linux (latest updated).

**Comment by vlaaad** [comment]
Can you post full stack trace?

**Comment by seancorfield** [comment]
What version of `lein` are you using? What's in your `~/.lein/profiles.clj` file? (often things in there interfere with running some projects)

**Comment by ahungry** [comment]
```
lein --version
Leiningen 2.8.3 on Java 11.0.3 OpenJDK 64-Bit Server VM
```

Stacktrace:
```
Exception in thread "main" Syntax error compiling at (cljfx/core.clj:1:1).                                                                                                                                                             [20/144]
        at clojure.lang.Compiler.load(Compiler.java:7647)         
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:463)             
        at clojure.lang.RT.load(RT.java:428)                 
        at clojure.core$load$fn__6824.invoke(core.clj:6126)   
        at clojure.core$load.invokeStatic(core.clj:6125)   
        at clojure.core$load.doInvoke(core.clj:6109) 
        at clojure.lang.RestFn.invoke(RestFn.java:408)       
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5985)                                                                  
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)   
        at clojure.core$require.invokeStatic(core.clj:6007)
        at clojure.core$require.doInvoke(core.clj:6007)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at user$eval140$fn__144.invoke(form-init5339610884014396360.clj:1)
        at user$eval140.invokeStatic(form-init5339610884014396360.clj:1)
        at user$eval140.invoke(form-init5339610884014396360.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)   
        at clojure.lang.Compiler.eval(Compiler.java:7166)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        at clojure.lang.Compiler.loadFile(Compiler.java:7573)
        at clojure.main$load_script.invokeStatic(main.clj:452)
        at clojure.main$init_opt.invokeStatic(main.clj:454)
        at clojure.main$init_opt.invoke(main.clj:454)  
        at clojure.main$initialize.invokeStatic(main.clj:485)
        at clojure.main$null_opt.invokeStatic(main.clj:519)
        at clojure.main$null_opt.invoke(main.clj:516)  
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)                        
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)               
Caused by: java.io.FileNotFoundException: Could not locate cljfx/api__init.class, cljfx/api.clj or cljfx/api.cljc on classpath.
        at clojure.lang.RT.load(RT.java:466)             
        at clojure.lang.RT.load(RT.java:428)
        at clojure.core$load$fn__6824.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5985)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$require.invokeStatic(core.clj:6007)
        at clojure.core$require.doInvoke(core.clj:6007)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at cljfx.core$eval157$loading__6706__auto____158.invoke(core.clj:1)
        at cljfx.core$eval157.invokeStatic(core.clj:1)
        at cljfx.core$eval157.invoke(core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)
        at clojure.lang.Compiler.eval(Compiler.java:7165)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        ... 40 more
```

**Comment by ahungry** [comment]
```
java -version                                                                                                                                                                                                 
openjdk version "11.0.3" 2019-04-16                                                                                                                                                                                                           
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)                                                                                                                                                                           
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```

Nothing in lein profiles directory.

Maybe I'll find time to make a minimal sample Dockerfile that can reproduce this issue.

**Comment by vlaaad** [comment]
Can you show me an output of `lein run` if you change `src/lein_cljfx_test/core.clj` like that?
```clj
(ns lein-cljfx-test.core)

(defn -main [& args]
  (println *clojure-version*)
  (println (System/getProperty "java.vm.version")))
```

**Comment by ahungry** [comment]
```
{:major 1, :minor 10, :incremental 0, :qualifier nil}
11.0.3+7-Ubuntu-1ubuntu218.04.1
```

**Comment by vlaaad** [comment]
Well, requirements are met.. Can you try effectively the same snippet using JavaFX only to see if it's related to cljfx or javafx?
To do it, modify `project.clj` to be like that:
```edn
(defproject lein-cljfx-test "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [org.openjfx/javafx-base "12"]
                 [org.openjfx/javafx-graphics "12"]
                 [org.openjfx/javafx-controls "12"]]
  :main lein-cljfx-test.core)
```
And `src/lein_cljfx_test/core.clj` to be like that:
```clj
(ns lein-cljfx-test.core
  (:import [javafx.application Platform]
           [javafx.scene Scene]
           [javafx.stage Stage]
           [javafx.scene.control Label]
           [javafx.scene.layout VBox]))

(defn -main [& args]
  (Platform/startup #(prn :started))
  (Platform/runLater
    #(doto (Stage.)
       (.setScene (Scene.
                    (doto (VBox.)
                      (-> .getChildren (.add (Label. "Hello from lein"))))))
       (.show))))

```

**Comment by ahungry** [comment]
That worked with direct inclusion, I received the GUI printing Hello from lein as expected.

**Comment by vlaaad** [comment]
Hmm, not sure what to do next... I also noticed that exception has `(cljfx/core.clj:1:1)` in it, but cljfx does not have a `cljfx/core.clj` file, is it a file you created yourself and required `cljfx.api` from it? Maybe `lein` is confused and expects to find `cljfx/api.clj` in your source directory? Or it can't properly add `cljfx` to your classpath for some reason and `lein clean` can help? What is `lein deps :tree` output for your when cljfx is present in `:dependencies`?

**Comment by ahungry** [comment]
Yea sorry, my entry point file for this project was created with `lein new app cljfx` vs `lein new app lein-cljfx-test`, so thats essentially referencing the lein-cljfx-test core from your given instructions.

At least deps.edn works well with this :laughing:  gives me a good reason to get aboard the deps train.

**Comment by vlaaad** [comment]
Can you try with differently named lein project? It might be that lein thinks that `cljfx` is your project, not a dependency, because they have the same name.

**Comment by victorb** [comment]
@vlaaad another thing. Seems `lein uberjar` never finishes it's build, unsure of why. Seems there is maybe some issue with when clojure runs the classes static initializer and something gets started, which never gets closed afterwards.

Copying the example you made above:

```
(ns lein-cljfx-test.core
  (:require [cljfx.api :as fx])
  (:gen-class)
  (:import [javafx.application Platform]))

(defn -main [& args]
  (Platform/setImplicitExit true)
  (fx/on-fx-thread
    (fx/create-component
      {:fx/type :stage
       :showing true
       :scene {:fx/type :scene
               :root {:fx/type :v-box
                      :children [{:fx/type :label
                                  :text "Hello from lein!"}]}}})))
```

Runs fine with `lein run` (and thanks to `setImplicitExit`, also exits the full application when closing the javafx application)

However, running `lein uberjar` with that example, leads to the lein getting stuck at `Compiling lein-cljfx-test.core` forever (seemingly, I let it run for 20 minutes)

Running `strace -f lein uberjar` also confirms that it's waiting for something, but that something never happens.

Any advice on what could be happening?

(using clojure 1.10.0 + cljfx 1.2.10 with both openjdk and jdk version 11)

**Comment by vlaaad** [comment]
@victorb I created #17 for this discussion, it's a separate issue.

@ahungry does lein work for you if you create project with different name (not `cljfx`)?

**Comment by ahungry** [comment]
@vlaaad I can confirm after a rename of the project, no more issue.  Thanks for the assist and feel free to close this :)

**Comment by vlaaad** [comment]
Glad that it worked for you!
