### ISSUE TITLE
Question : list-view/with-selection-props gives error " No such prop: :v-box/vgrow {:prop :v-box/vgrow}"

### ISSUE THREAD

**Issue by pasdut** [cljfx/cljfx#151]
Hi,
When I want to set  `:v-box/vgrow`  on a list view created via ` fx.ext.list-view/with-selection-props` I get the following error :
` No such prop: :v-box/vgrow {:prop :v-box/vgrow}`

In the example below, I can set the `vgrow` on a normal list-view (the one that contains `["one" "two"]` in the example).
But I get the error when I also want to set `vgrow` on the second list-view (contains `["first" "second" "third"]`).

Maybe this isn't possible ?

Thanks in advance for your help,

Pascal

```

(ns cljfx-voorbeeld.core
  (:gen-class)
  (:require [cljfx.api :as fx]
            [cljfx.ext.list-view :as fx.ext.list-view]))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!"))

(comment

  (fx/on-fx-thread
     (fx/create-component
      {:fx/type :stage
       :showing true
       :title "Cljfx example"
       :width 800
       :height 600
       :scene {:fx/type :scene
               :root {:fx/type :v-box
                      :children [{:fx/type :label
                                  :text "Hello world"}
                                 {:fx/type :list-view
                                         :v-box/vgrow :always
                                  :items ["one" "two"]}
                                 {:fx/type fx.ext.list-view/with-selection-props
                                  :props {:selection-mode :single}
                                  :desc {:fx/type :list-view
                                         :v-box/vgrow :always ;; <------- THIS ONE CAUSES THE ERROR
                                         :items ["first" "second" "third"]}}]}}}))

  )
```
The complete stacktrace : 

```
clojure.lang.ExceptionInfo: No such prop: :v-box/vgrow {:prop :v-box/vgrow}
	at cljfx.composite$create_props$fn__16013.invoke(composite.clj:21)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8437.invokeStatic(core.clj:6845)
	at clojure.core$fn__8437.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at clojure.core$reduce_kv.invoke(core.clj:6847)
	at cljfx.composite$create_props.invokeStatic(composite.clj:17)
	at cljfx.composite$create_props.invoke(composite.clj:16)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
	at cljfx.composite$create_composite_component.invoke(composite.clj:26)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:29)
	at cljfx.lifecycle$reify__1164.create(lifecycle.clj:39)
	at cljfx.lifecycle$make_ext_with_props$reify__1366.create(lifecycle.clj:407)
	at cljfx.lifecycle$make_ext_with_props$reify__1366.create(lifecycle.clj:407)
	at cljfx.lifecycle$wrap_map_desc$fn__1382.invoke(lifecycle.clj:446)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$make_ext_with_props$reify__1366.create(lifecycle.clj:407)
	at cljfx.lifecycle$wrap_map_desc$fn__1382.invoke(lifecycle.clj:446)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:29)
	at cljfx.lifecycle$reify__1164.create(lifecycle.clj:39)
	at cljfx.lifecycle$wrap_extra_props$fn__1298.invoke(lifecycle.clj:348)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$wrap_many$fn__1254$fn__1258$fn__1259.invoke(lifecycle.clj:279)
	at clojure.core$update.invokeStatic(core.clj:6196)
	at clojure.core$update.invoke(core.clj:6188)
	at cljfx.lifecycle$wrap_many$fn__1254$fn__1258.invoke(lifecycle.clj:279)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at cljfx.lifecycle$wrap_many$fn__1254.invoke(lifecycle.clj:278)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.composite$create_props$fn__16013.invoke(composite.clj:22)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8437.invokeStatic(core.clj:6845)
	at clojure.core$fn__8437.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at clojure.core$reduce_kv.invoke(core.clj:6847)
	at cljfx.composite$create_props.invokeStatic(composite.clj:17)
	at cljfx.composite$create_props.invoke(composite.clj:16)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
	at cljfx.composite$create_composite_component.invoke(composite.clj:26)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:29)
	at cljfx.lifecycle$reify__1164.create(lifecycle.clj:39)
	at cljfx.composite$create_props$fn__16013.invoke(composite.clj:22)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8437.invokeStatic(core.clj:6845)
	at clojure.core$fn__8437.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at clojure.core$reduce_kv.invoke(core.clj:6847)
	at cljfx.composite$create_props.invokeStatic(composite.clj:17)
	at cljfx.composite$create_props.invoke(composite.clj:16)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
	at cljfx.composite$create_composite_component.invoke(composite.clj:26)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:29)
	at cljfx.lifecycle$reify__1164.create(lifecycle.clj:39)
	at cljfx.composite$create_props$fn__16013.invoke(composite.clj:22)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8437.invokeStatic(core.clj:6845)
	at clojure.core$fn__8437.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at clojure.core$reduce_kv.invoke(core.clj:6847)
	at cljfx.composite$create_props.invokeStatic(composite.clj:17)
	at cljfx.composite$create_props.invoke(composite.clj:16)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
	at cljfx.composite$create_composite_component.invoke(composite.clj:26)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$wrap_on_delete$fn__1375.invoke(lifecycle.clj:435)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:32)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:29)
	at cljfx.lifecycle$reify__1164.create(lifecycle.clj:39)
	at cljfx.lifecycle$fn__1168.invokeStatic(lifecycle.clj:58)
	at cljfx.lifecycle$fn__1168.invoke(lifecycle.clj:56)
	at cljfx.lifecycle$eval1092$fn__1114$G__1079__1123.invoke(lifecycle.clj:17)
	at cljfx.api$create_component.invokeStatic(api.clj:117)
	at cljfx.api$create_component.invoke(api.clj:103)
	at cljfx.api$create_component.invokeStatic(api.clj:115)
	at cljfx.api$create_component.invoke(api.clj:103)
	at cljfx_voorbeeld.core$eval18142$fn__18143$fn__18147.invoke(form-init9144592159434563453.clj:20)
	at cljfx_voorbeeld.core$eval18142$fn__18143.invoke(form-init9144592159434563453.clj:19)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by vlaaad** [comment]
Move :v-box/vgrow :always one map higher

**Comment by vlaaad** [comment]
The same principle applies here as it applies to :fx/key — https://github.com/cljfx/cljfx#fxkey-should-be-put-on-descriptions-in-a-list-not-inside-these-descriptions

:v-box/vgrow is only valid on a map in a children list of a v box, not on some nested map

**Comment by pasdut** [comment]
Hi Vlaaad,

Thank you very much for the quick response. That fixed it indeed. 
I included the working example as a reference for other people :
```
(fx/on-fx-thread
     (fx/create-component
      {:fx/type :stage
       :showing true
       :title "Cljfx example"
       :width 800
       :height 600
       :scene {:fx/type :scene
               :root {:fx/type :v-box
                      :children [{:fx/type :label
                                  :text "Hello world"}
                                 {:fx/type :list-view
                                  :v-box/vgrow :always
                                  :items ["one" "two"]}
                                 {:fx/type fx.ext.list-view/with-selection-props
                                  :props {:selection-mode :single}
                                  :v-box/vgrow :always  ;; <------- THIS ONE SOLVED THE ISSUE
                                  :desc {:fx/type :list-view
                                         ;; :v-box/vgrow :always ;; <------- THIS ONE CAUSES THE ERROR
                                         :items ["first" "second" "third"]}}]}}}))
```
