### ISSUE TITLE
how to set the background of a region

### ISSUE THREAD

**Issue by challmand** [cljfx/cljfx#172]
Hello, I am trying to set the background image of a stack-pane, but I cannot seem to figure it out. 

This is the code I am working with 

```
  (fx/on-fx-thread
   (fx/create-component
    {:fx/type :stage
     :max-width 1253
     :max-height 860
     :showing true
     :title "Votann"
     :scene {:fx/type :scene
             :root {:fx/type :stack-pane
                    :background (cljfx.coerce/background
                                 [(BackgroundImage. (Image. "file:/home/Pictures/Screenshots/background.png") nil nil nil nil)])
                    :children [{:fx/type :tab-pane
                                :tabs unit-tabs}]}}})))
```

and this is the error i am getting

```
clojure.lang.ExceptionInfo: Don't know how to coerce {:target javafx.scene.layout.Background, :x [#object[javafx.scene.layout.BackgroundImage 0x642c5db5 "javafx.scene.layout.BackgroundImage@e705aa5d"]]}
	at cljfx.coerce$fail.invokeStatic(coerce.clj:43)
	at cljfx.coerce$fail.invoke(coerce.clj:42)
	at cljfx.coerce$background.invokeStatic(coerce.clj:320)
	at cljfx.coerce$background.invoke(coerce.clj:315)
	at votann.core$_main$fn__1895$fn__1899.invoke(core.clj:166)
	at votann.core$_main$fn__1895.invoke(core.clj:157)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Is there logic that I am missing? Appreciate any help with this.

**Comment by challmand** [comment]
looks like 

```
:background (cljfx.coerce/background
                                {:image (BackgroundImage. (Image. "file:/home/Pictures/Screenshots/background.png") nil nil nil nil)})
```

allows me to compile, but the background image does not show. are there any examples setting the background to an image without css?

**Comment by challmand** [comment]
and this returns true, so guess that isnt correct

```
  (println (.isEmpty (cljfx.coerce/background
                                {:image (BackgroundImage. (Image. "https://i.imgur.com/fnQsWyw.jpeg") nil nil nil nil)})))
```

**Comment by vlaaad** [comment]
This worked for me:
```clj
(fx/on-fx-thread
  (fx/create-component
    {:fx/type :stage
     :width 960
     :height 540
     :showing true
     :scene {:fx/type :scene
             :root {:fx/type :stack-pane
                    :background {:images ["file:/Users/vlaaad/Desktop/Screenshot 2023-06-05 at 11.42.53.png"]}
                    :children [{:fx/type :label
                                :text-fill :white
                                :text "Hello world!"}]}}}))
```

**Comment by vlaaad** [comment]
`:background` is a map with `:images` and/or `:fills` keys. Here is what [cljfx.dev](https://github.com/cljfx/dev) says about background:
```clj
(cljfx.dev/help :stack-pane :background)
Prop of :stack-pane - :background

Background, either:
- a map with optional keys:
  - :fills - a coll of background fills¹
  - :images - a coll of background images²
- instance of javafx.scene.layout.Background

---
¹background fills - Background fill, either:
 - map with optional :fill³, :radii⁴ and :insets⁵ keys
 - instance of javafx.scene.layout.BackgroundFill

²background images - Background image is either:
 - string: either a resource path or URL string pointing to image
 - map with keys:
   - :image - image⁶, required
   - :repeat-x - either of: :no-repeat, :repeat, :round, :space⁷
   - :repeat-y - either of: :no-repeat, :repeat, :round, :space⁷
   - :position - background position⁸
   - :size - background size⁹
 - instance of javafx.scene.layout.BackgroundImage

³:fill - Paint, either:
 - color¹⁰
 - 2-element tuple of :linear-gradient and a map with required keys:
   - :start-x - double
   - :start-y - double
   - :end-x - double
   - :end-y - double
   - :proportional - boolean
   - :cycle method - either of: :no-cycle, :reflect, :repeat¹¹
   - :stops - a coll of 2-element tuples of double and color¹⁰
 - 2-element tuple of :radial-gradient and a map with required keys:
   - :focus-angle - double
   - :focus-distance - double
   - :center-x - double
   - :center-y - double
   - :radius - double
   - :proportional - boolean
   - :cycle-method - either of: :no-cycle, :reflect, :repeat¹¹
 - 2-element tuple of :image-pattern and a map with keys:
   - :image - image⁶, required
   - :x - double
   - :y - double
   - :width - double
   - :height - double
   - :proportional - boolean
 - instance of javafx.scene.paint.Paint

⁴:radii - Corner radii, either:
 - literal :empty
 - number - a corner radius
 - a map with required either :radius (number) or both :top-left, :top-right, :bottom-right and :bottom-left keys (numbers), and optional :as-percent boolean key
 - instance of javafx.scene.layout.CornerRadii

⁵:insets - Insets, either:
 - number
 - map with optional keys - :top, :bottom, :left, :right - numbers
 - literal - :empty
 - instance of javafx.geometry.Insets

⁶image - Image, either:
 - instance of javafx.scene.image.Image
 - string: either a resource path or URL string pointing to image
 - map with required :url (url string) or :is (input stream) keys and optional :requested-width (number), :requested-height (number), :preserve-ratio (boolean), :smooth (boolean) and :background-loading (boolean) keys

⁷either of: :no-repeat, :repeat, :round, :space - Enum:
 javafx.scene.layout.BackgroundRepeat
 
 Idiomatic values:
 - :no-repeat
 - :repeat
 - :round
 - :space
 
 Also works:
 - javafx.scene.layout.BackgroundRepeat/NO_REPEAT
 - javafx.scene.layout.BackgroundRepeat/REPEAT
 - javafx.scene.layout.BackgroundRepeat/ROUND
 - javafx.scene.layout.BackgroundRepeat/SPACE

⁸background position - Background image position, either:
 - literal - :center or :default
 - a map with required :horizontal and :vertical keys (background position axes¹²)
 - instance of javafx.scene.layout.BackgroundPosition

⁹background size - Background image size, either:
 - literal - :auto or :default
 - a map with keys:
   - :width - number, required
   - :height - number, required
   - :width-as-percentage - boolean
   - :height-as-percentage - boolean
   - :contain - boolean
   - :cover - boolean
 - instance of javafx.scene.layout.BackgroundSize

¹⁰color - A color, either:
 - string in either format:
   - 0x0000FF - 0x-prefixed hex web value
   - 0x00F - 0x-prefixed short hex web value
   - #0000FF - #-prefixed hex web value
   - #00F - #-prefixed short hex web value
   - 0000FF - hex web value
   - 00F - short hex web value
   - rgba(0,0,255,1.0) - rgb web value, explicit alpha
   - rgb(0,0,255) - rgb web value, implicit alpha
   - rgba(0,0,100%,1.0) - rgb percent web value, explicit alpha
   - rgb(0,0,100%) - rgb percent web value, implicit alpha
   - hsla(270,100%,100%,1.0) - hsl web value, explicit alpha
   - hsl(270,100%,100%) - hsl web value, implicit alpha
 - instance of javafx.scene.paint.Color
 - keyword of a named color:
   - :aliceblue
   - :antiquewhite
   - :aqua
   - :aquamarine
   - :azure
   - :beige
   - :bisque
   - :black
   - :blanchedalmond
   - :blue
   - :blueviolet
   - :brown
   - :burlywood
   - :cadetblue
   - :chartreuse
   - :chocolate
   - :coral
   - :cornflowerblue
   - :cornsilk
   - :crimson
   - :cyan
   - :darkblue
   - :darkcyan
   - :darkgoldenrod
   - :darkgray
   - :darkgreen
   - :darkgrey
   - :darkkhaki
   - :darkmagenta
   - :darkolivegreen
   - :darkorange
   - :darkorchid
   - :darkred
   - :darksalmon
   - :darkseagreen
   - :darkslateblue
   - :darkslategray
   - :darkslategrey
   - :darkturquoise
   - :darkviolet
   - :deeppink
   - :deepskyblue
   - :dimgray
   - :dimgrey
   - :dodgerblue
   - :firebrick
   - :floralwhite
   - :forestgreen
   - :fuchsia
   - :gainsboro
   - :ghostwhite
   - :gold
   - :goldenrod
   - :gray
   - :green
   - :greenyellow
   - :grey
   - :honeydew
   - :hotpink
   - :indianred
   - :indigo
   - :ivory
   - :khaki
   - :lavender
   - :lavenderblush
   - :lawngreen
   - :lemonchiffon
   - :lightblue
   - :lightcoral
   - :lightcyan
   - :lightgoldenrodyellow
   - :lightgray
   - :lightgreen
   - :lightgrey
   - :lightpink
   - :lightsalmon
   - :lightseagreen
   - :lightskyblue
   - :lightslategray
   - :lightslategrey
   - :lightsteelblue
   - :lightyellow
   - :lime
   - :limegreen
   - :linen
   - :magenta
   - :maroon
   - :mediumaquamarine
   - :mediumblue
   - :mediumorchid
   - :mediumpurple
   - :mediumseagreen
   - :mediumslateblue
   - :mediumspringgreen
   - :mediumturquoise
   - :mediumvioletred
   - :midnightblue
   - :mintcream
   - :mistyrose
   - :moccasin
   - :navajowhite
   - :navy
   - :oldlace
   - :olive
   - :olivedrab
   - :orange
   - :orangered
   - :orchid
   - :palegoldenrod
   - :palegreen
   - :paleturquoise
   - :palevioletred
   - :papayawhip
   - :peachpuff
   - :peru
   - :pink
   - :plum
   - :powderblue
   - :purple
   - :red
   - :rosybrown
   - :royalblue
   - :saddlebrown
   - :salmon
   - :sandybrown
   - :seagreen
   - :seashell
   - :sienna
   - :silver
   - :skyblue
   - :slateblue
   - :slategray
   - :slategrey
   - :snow
   - :springgreen
   - :steelblue
   - :tan
   - :teal
   - :thistle
   - :tomato
   - :transparent
   - :turquoise
   - :violet
   - :wheat
   - :white
   - :whitesmoke
   - :yellow
   - :yellowgreen

¹¹either of: :no-cycle, :reflect, :repeat - Enum:
  javafx.scene.paint.CycleMethod
  
  Idiomatic values:
  - :no-cycle
  - :reflect
  - :repeat
  
  Also works:
  - javafx.scene.paint.CycleMethod/NO_CYCLE
  - javafx.scene.paint.CycleMethod/REFLECT
  - javafx.scene.paint.CycleMethod/REPEAT

¹²background position axes - Background image position axis, a map with keys:
  - :position - a number, required
  - :side - either of: :bottom, :left, :right, :top¹³
  - :as-percentage - boolean

¹³either of: :bottom, :left, :right, :top - Enum:
  javafx.geometry.Side
  
  Idiomatic values:
  - :bottom
  - :left
  - :right
  - :top
  
  Also works:
  - javafx.geometry.Side/BOTTOM
  - javafx.geometry.Side/LEFT
  - javafx.geometry.Side/RIGHT
  - javafx.geometry.Side/TOP
```

**Comment by challmand** [comment]
youre awesome, thank you for the help and creating this useful library.
