### ISSUE TITLE
Obscure classloader problem in cider

### ISSUE THREAD

**Issue by jdf-id-au** [cljfx/cljfx#177]
Hi, thanks again for a brilliant library.

I'm scratching my head about this one.

Using Clojure 1.11.1, OpenJDK 17, macOS 14.2.1, this works fine:
```
$ clj -M:examples
user=> (load "e28_canvas")
```

But using the same tools via CIDER in emacs (`cider-jack-in-clj` specifying the `:examples` alias, and running `cider-load-buffer` within `e28_canvas.clj`) gives an error (condensed):
```
[nREPL] Starting server via /usr/local/bin/clojure -Sdeps \{\:deps\ \{nrepl/nrepl\ \{\:mvn/version\ \"1.0.0\"\}\ cider/cider-nrepl\ \{\:mvn/version\ \"0.44.0\"\}\}\ \:aliases\ \{\:cider/nrepl\ \{\:main-opts\ \[\"-m\"\ \"nrepl.cmdline\"\ \"--middleware\"\ \"\[cider.nrepl/cider-middleware\]\"\]\}\}\} -M:cider/nrepl:examples
Loading /path/to/cljfx/examples/e28_canvas.clj...
=> Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class javafx.scene.control.Slider
```

Sometimes it's `Control` rather than `Slider`. The exception originates from the call to `create-props` in `create-composite-component` in `cljfx.composite`.

This did not happen in the past, but I haven't been able to determine which change in which system component caused it!

Empirically the only difference betwen `(System/getProperty "java.class.path")` between the two is the presence of cider-related jars `orchard`, `nrepl`, `logjam` and `cider-nrepl`.

Is there an obvious way I can investigate this further?

**Comment by jm-g** [comment]
I do observe this problem as well. One additional remark I can paste the first example from cljfx's readme into the cider repl and it works. If I evaluate the same code from a buffer it fails.

**Comment by jdf-id-au** [comment]
I was also able to get it going by running nrepl within my project and using `cider-connect-clj`... 🧐

**Comment by vlaaad** [comment]
Could you try launching JDK from emacs and the command line and checking if `(System/getProperty "os.arch")` returns different results?

**Comment by jdf-id-au** [comment]
Both `x86_64`

**Comment by jdf-id-au** [comment]
Revisiting this in openjdk@21, clojure 1.11.1, cljfx 1.9.3 with the benefit of clearer exception reporting. Works fine from `clj -M:jdk17:examples`, doesn't work from cider with same aliases loaded. I think I'm missing something obvious about the thread in which initialisation occurs.

```
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class javafx.scene.control.Control
	at cljfx.fx.slider$fn__13093.invokeStatic(slider.clj:39)
	at cljfx.fx.slider$fn__13093.invoke(slider.clj:39)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:31)
	at cljfx.composite$create_composite_component.invoke(composite.clj:26)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
	at cljfx.lifecycle$reify__11197.create(lifecycle.clj:43)
	at cljfx.lifecycle$wrap_extra_props$fn__11330.invoke(lifecycle.clj:369)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.lifecycle$wrap_many$fn__11286$fn__11290$fn__11291.invoke(lifecycle.clj:300)
	at clojure.core$update.invokeStatic(core.clj:6231)
	at clojure.core$update.invoke(core.clj:6223)
	at cljfx.lifecycle$wrap_many$fn__11286$fn__11290.invoke(lifecycle.clj:300)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at cljfx.lifecycle$wrap_many$fn__11286.invoke(lifecycle.clj:299)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.composite$create_props$fn__11939.invoke(composite.clj:22)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
	at clojure.core$fn__8525.invokeStatic(core.clj:6908)
	at clojure.core$fn__8525.invoke(core.clj:6888)
	at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6919)
	at clojure.core$reduce_kv.invoke(core.clj:6910)
	at cljfx.composite$create_props.invokeStatic(composite.clj:17)
	at cljfx.composite$create_props.invoke(composite.clj:16)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
	at cljfx.composite$create_composite_component.invoke(composite.clj:26)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
	at cljfx.lifecycle$reify__11197.create(lifecycle.clj:43)
	at cljfx.composite$create_props$fn__11939.invoke(composite.clj:22)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
	at clojure.core$fn__8525.invokeStatic(core.clj:6908)
	at clojure.core$fn__8525.invoke(core.clj:6888)
	at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6919)
	at clojure.core$reduce_kv.invoke(core.clj:6910)
	at cljfx.composite$create_props.invokeStatic(composite.clj:17)
	at cljfx.composite$create_props.invoke(composite.clj:16)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
	at cljfx.composite$create_composite_component.invoke(composite.clj:26)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
	at cljfx.lifecycle$reify__11197.create(lifecycle.clj:43)
	at cljfx.composite$create_props$fn__11939.invoke(composite.clj:22)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
	at clojure.core$fn__8525.invokeStatic(core.clj:6908)
	at clojure.core$fn__8525.invoke(core.clj:6888)
	at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6919)
	at clojure.core$reduce_kv.invoke(core.clj:6910)
	at cljfx.composite$create_props.invokeStatic(composite.clj:17)
	at cljfx.composite$create_props.invoke(composite.clj:16)
	at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
	at cljfx.composite$create_composite_component.invoke(composite.clj:26)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.lifecycle$wrap_on_delete$fn__11407.invoke(lifecycle.clj:457)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
	at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
	at cljfx.lifecycle$reify__11197.create(lifecycle.clj:43)
	at cljfx.lifecycle$fn__11201.invokeStatic(lifecycle.clj:62)
	at cljfx.lifecycle$fn__11201.invoke(lifecycle.clj:60)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.lifecycle$wrap_map_desc$fn__11414.invoke(lifecycle.clj:468)
	at cljfx.lifecycle$eval11124$fn__11146$G__11111__11155.invoke(lifecycle.clj:18)
	at cljfx.renderer$render_component.invokeStatic(renderer.clj:59)
	at cljfx.renderer$render_component.invoke(renderer.clj:49)
	at cljfx.renderer$create$fn__11832.invoke(renderer.clj:79)
	at cljfx.renderer$perform_render$fn__11766.invoke(renderer.clj:23)
	at cljfx.renderer$perform_render.invokeStatic(renderer.clj:22)
	at cljfx.renderer$perform_render.invoke(renderer.clj:14)
	at cljfx.renderer$request_render$fn__11792$fn__11796.invoke(renderer.clj:45)
	at cljfx.renderer$request_render$fn__11792.invoke(renderer.clj:45)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Toolkit not initialized [in thread "clojure-agent-send-off-pool-0"]
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:436)
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:431)
	at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:724)
	at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:686)
	at javafx.scene.control.Control.<clinit>(Control.java:98)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang
```

**Comment by vlaaad** [comment]
Do you somehow have `(Boolean/getBoolean "cljfx.skip-javafx-initialization")` set to `true`?
