### ISSUE TITLE
Error: No implementation of method: :create of protocol: #'cljfx.lifecycle/Lifecycle found for class: nil

### ISSUE THREAD

**Issue by ejstembler** [cljfx/cljfx#183]
I sometimes encounter this error I don't quite understand:

```console
java.lang.IllegalArgumentException: No implementation of method: :create of protocol: #'cljfx.lifecycle/Lifecycle found for class: nil
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:584)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:576)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
        at cljfx.lifecycle$reify__2534.create(lifecycle.clj:43)
        at cljfx.composite$create_props$fn__3415.invoke(composite.clj:22)
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
        at clojure.core$fn__8525.invokeStatic(core.clj:6909)
        at clojure.core$fn__8525.invoke(core.clj:6889)
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6920)
        at clojure.core$reduce_kv.invoke(core.clj:6911)
        at cljfx.composite$create_props.invokeStatic(composite.clj:17)
        at cljfx.composite$create_props.invoke(composite.clj:16)
        at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
        at cljfx.composite$create_composite_component.invoke(composite.clj:26)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
        at cljfx.lifecycle$reify__2534.create(lifecycle.clj:43)
        at cljfx.lifecycle$wrap_extra_props$fn__2667.invoke(lifecycle.clj:369)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$wrap_many$fn__2623$fn__2627$fn__2628.invoke(lifecycle.clj:300)
        at clojure.core$update.invokeStatic(core.clj:6232)
        at clojure.core$update.invoke(core.clj:6224)
        at cljfx.lifecycle$wrap_many$fn__2623$fn__2627.invoke(lifecycle.clj:300)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6869)
        at cljfx.lifecycle$wrap_many$fn__2623.invoke(lifecycle.clj:299)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.composite$create_props$fn__3415.invoke(composite.clj:22)
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
        at clojure.core$fn__8525.invokeStatic(core.clj:6909)
        at clojure.core$fn__8525.invoke(core.clj:6889)
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6920)
        at clojure.core$reduce_kv.invoke(core.clj:6911)
        at cljfx.composite$create_props.invokeStatic(composite.clj:17)
        at cljfx.composite$create_props.invoke(composite.clj:16)
        at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
        at cljfx.composite$create_composite_component.invoke(composite.clj:26)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
        at cljfx.lifecycle$reify__2534.create(lifecycle.clj:43)
        at cljfx.lifecycle$wrap_extra_props$fn__2667.invoke(lifecycle.clj:369)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$wrap_many$fn__2623$fn__2627$fn__2628.invoke(lifecycle.clj:300)
        at clojure.core$update.invokeStatic(core.clj:6232)
        at clojure.core$update.invoke(core.clj:6224)
        at cljfx.lifecycle$wrap_many$fn__2623$fn__2627.invoke(lifecycle.clj:300)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6869)
        at cljfx.lifecycle$wrap_many$fn__2623.invoke(lifecycle.clj:299)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.composite$create_props$fn__3415.invoke(composite.clj:22)
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
        at clojure.core$fn__8525.invokeStatic(core.clj:6909)
        at clojure.core$fn__8525.invoke(core.clj:6889)
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6920)
        at clojure.core$reduce_kv.invoke(core.clj:6911)
        at cljfx.composite$create_props.invokeStatic(composite.clj:17)
        at cljfx.composite$create_props.invoke(composite.clj:16)
        at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
        at cljfx.composite$create_composite_component.invoke(composite.clj:26)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
        at cljfx.lifecycle$reify__2534.create(lifecycle.clj:43)
        at cljfx.composite$create_props$fn__3415.invoke(composite.clj:22)
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
        at clojure.core$fn__8525.invokeStatic(core.clj:6909)
        at clojure.core$fn__8525.invoke(core.clj:6889)
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6920)
        at clojure.core$reduce_kv.invoke(core.clj:6911)
        at cljfx.composite$create_props.invokeStatic(composite.clj:17)
        at cljfx.composite$create_props.invoke(composite.clj:16)
        at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
        at cljfx.composite$create_composite_component.invoke(composite.clj:26)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
        at cljfx.lifecycle$reify__2534.create(lifecycle.clj:43)
        at cljfx.composite$create_props$fn__3415.invoke(composite.clj:22)
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
        at clojure.core$fn__8525.invokeStatic(core.clj:6909)
        at clojure.core$fn__8525.invoke(core.clj:6889)
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6920)
        at clojure.core$reduce_kv.invoke(core.clj:6911)
        at cljfx.composite$create_props.invokeStatic(composite.clj:17)
        at cljfx.composite$create_props.invoke(composite.clj:16)
        at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
        at cljfx.composite$create_composite_component.invoke(composite.clj:26)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$wrap_on_delete$fn__2744.invoke(lifecycle.clj:457)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:36)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:33)
        at cljfx.lifecycle$reify__2534.create(lifecycle.clj:43)
        at cljfx.lifecycle$fn__2538.invokeStatic(lifecycle.clj:62)
        at cljfx.lifecycle$fn__2538.invoke(lifecycle.clj:60)
        at cljfx.lifecycle$eval2461$fn__2483$G__2448__2492.invoke(lifecycle.clj:18)
        at cljfx.api$create_component.invokeStatic(api.clj:121)
        at cljfx.api$create_component.invoke(api.clj:107)
        at cljfx.api$create_component.invokeStatic(api.clj:119)
        at cljfx.api$create_component.invoke(api.clj:107)
        at clj_money.core$_main$fn__3374$fn__3378.invoke(core.clj:13)
        at clj_money.core$_main$fn__3374.invoke(core.clj:12)
        at clojure.lang.AFn.run(AFn.java:22)
        at javafx.graphics@22.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@22.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at javafx.graphics@22.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

It's related to setting the `graphic` keyword to a function result.  For example:

```clojure
(ns my-namespace
  (:require [cljfx.api :as fx])
  (:import [org.kordamp.ikonli.javafx FontIcon]
           [org.kordamp.ikonli.materialdesign2 MaterialDesignB MaterialDesignS])
  (:gen-class))

(defn code->font-icon
  [icon-code]
  {:pre [(some? icon-code)]
   :post [(some? %) (instance? FontIcon %)]}
  ;; Create a FontIcon and set the icon code directly using interop
  (doto (FontIcon.)
    (.setIconCode icon-code)))

(defn dashboard-view
  [data]
  ;; snip...
  {:fx/type :split-pane
     :divider-positions [0.2]
     :items [{:fx/type :v-box
              :spacing 10
              :padding 10
              :children [{:fx/type :button
                                   :text "Dashboard"
                                   :graphic (code->font-icon MaterialDesignS/SPEEDOMETER)
                                   :content-display :left
                                   :alignment :center-left
                                   :style "-fx-font-size: 16px;"}
;; snip...
```

If I remove `graphic` the error goes away.

A simplified version doesn't work either:

```clojure
:graphic (FontIcon. MaterialDesignS/SPEEDOMETER)
```

**Comment by vlaaad** [comment]
Hi @ejstembler!
`:graphic` value should be a map with `:fx/type` key, not an instance of an icon. You can use `fx/ext-instance-factory`:
```clj
(def speedometer-icon-desc
  {:fx/type fx/ext-instance-factory
   :create #(code->font-icon MaterialDesignS/SPEEDOMETER)})

{:fx/type :button 
 :graphic speedometer-icon-desc
 ...}
```

**Comment by vlaaad** [comment]
The error you get is unfortunate: lookup of `:fx/type` keyword on an instance of the FontIcon returns nil. You can also use [cljfx/dev](https://github.com/cljfx/dev) to improve error messages

**Comment by ejstembler** [comment]
Thank you @vlaaad!
