### ISSUE TITLE
NPE using :date-picker

### ISSUE THREAD

**Issue by jdf-id-au** [cljfx/cljfx#49]
Thanks for a magnificent library. I've been using it (version 1.5.1) very happily for a while now, via the `fx/create-app` function, using map events, wrapped effects, and subscriptions to an `fx/context`.

I've run into a problem with `{:fx/type :date-picker}`. Its `:on-value-changed` map event correctly reaches the handler function, which correctly generates an effect description. I can manually fire the corresponding effect using this description at the repl, and the UI updates correctly.

However, when I try to let it act on the effect description in the usual way, I get a NullPointerException:

```
java.lang.NullPointerException
	at cljfx.event_handler$wrap_effects$dispatch_sync_BANG___30311.invoke(event_handler.clj:28)
	at cljfx.event_handler$process_event.invokeStatic(event_handler.clj:31)
	at cljfx.event_handler$process_event.invoke(event_handler.clj:30)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$binding_conveyor_fn$fn__5754.doInvoke(core.clj:2041)
	at clojure.lang.RestFn.applyTo(RestFn.java:146)
	at clojure.lang.Agent$Action.doRun(Agent.java:114)
	at clojure.lang.Agent$Action.run(Agent.java:163)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

If I mark the event map `:fx/sync true`, the application just hangs.

The effect description doesn't seem to make it to the effect function.

Can you tell what's going on from this description? I feel like I'm failing to understand some lifecycle or threading concept somewhere.

**Comment by jdf-id-au** [comment]
Oh man how embarrassing. Typo in the actual effect description.

**Comment by vlaaad** [comment]
Hi!
Glad that you solved the problem! Perhaps cljfx should show a better error message when it tries to perform the effect that does not exist. Created #50 for that.
