### ISSUE TITLE
Can't translate scene parallel camera

### ISSUE THREAD

**Issue by jpmonettas** [cljfx/cljfx#56]
I'm trying to move a scene camera but when I try to set it's translate-x property I'm getting :

```
clojure.lang.ExceptionInfo: No such prop: :translate-x {:prop :translate-x}
	at cljfx.composite$create_props$fn__17058.invoke(composite.clj:20)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8437.invokeStatic(core.clj:6845)
	at clojure.core$fn__8437.invoke(core.clj:6830)
```

Here is a minimal example that reproduce the issue : 
```clojure
(def app
  (fx/create-app (atom (fx/create-context {}))
                 :event-handler (fn [e])
                 :desc-fn (fn [_]
                            {:fx/type :stage
                             :showing true
                             :width 800
                             :height 600
                             :scene {:fx/type :scene                                       
                                     :camera {:fx/type :parallel-camera
                                              :translate-x 100}
                                     :root {:fx/type :group
                                            :children [{:fx/type :rectangle
                                                        :x 0
                                                        :y 0
                                                        :width 5
                                                        :height 5}]}}})))
```

Since cameras are javafx.scene.Node I should be able to move it like this or am I missing something?

**Comment by vlaaad** [comment]
That was a bug, I just released version `1.6.4` that fixes it. Good catch, thanks!
