### ISSUE TITLE
NPE running the example code

### ISSUE THREAD

**Issue by johntwill** [cljfx/cljfx#6]
The GUI comes up but I get NPE:

Exception in thread "main" java.lang.NullPointerException
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)

**Comment by vlaaad** [comment]
I assume you are running `clj -A:examples -m e01-basic`. When running examples that way, clojure expects to have a `-main` function, which examples don't have. In some of them, such as [examples/e12_interactive_development.clj](https://github.com/cljfx/cljfx/blob/master/examples/e12_interactive_development.clj), having `-main` does not make any sense, but others I think could have it. 
Preferred way to run examples for now is through repl though:
```bash
clj -A:examples
# Clojure 1.10
# user=> (require 'e15-task-tracker)
# nil ;; window appears
```

**Comment by johntwill** [comment]
Ok, got it.  Thanks!
